[package]
name = "lapce"
version = "0.0.1"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2018"

[dependencies]
lapce-core = { path = "./core" }
parking_lot = { version = "0.11.0", features = ["deadlock_detection"] }
druid = { path = "../druid/druid", features = ["svg"] }

[build-dependencies]
cc = "*"

[workspace]
members = ["lsp", "core", "proxy", "rpc"]
