[package]
name = "lapce"
version = "0.0.1"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
lapce-core = { path = "./core" }

[workspace]
members = ["lsp", "core", "proxy", "rpc"]
