[package]
name = "lapce"
version = "0.0.1"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2018"

[dependencies]
include_dir = "0.6.0"
tree-sitter-highlight = "0.3.0"
tree-sitter = "0.17.0"
toml = "0.5.6"
anyhow = "1.0.32"
strum = "0.19"
strum_macros = "0.19"
lazy_static = "1.4.0"
# piet-cairo = "0.0.6"
serde = "1.0"
serde_json = "1.0"
syntect = "3.2"
xi-core-lib = { path = "../xi-editor/rust/core-lib/" }
xi-rope = { path = "../xi-editor/rust/rope/" }
fzyr = "0.1.2"
uuid = { version = "0.7.4", features = ["v4"] }
lsp-types = "0.61.0"
druid = { git = "https://github.com/linebender/druid" }

[build-dependencies]
cc = "*"
