# --------------------------------- General --------------------------------------------

[[keymaps]]
key = "meta+p"
command = "palette"

[[keymaps]]
key = "meta+P"
command = "palette.command"

[[keymaps]]
key = "meta+e"
command = "toggle_code_lens"
mode = "i"

[[keymaps]]
key = "meta+,"
command = "open_settings"

[[keymaps]]
key = "meta+k meta+s"
command = "open_keyboard_shortcuts"

# --------------------------------- Basic editing ---------------------------------------

[[keymaps]]
key = "meta+z"
command = "undo"

[[keymaps]]
key = "meta+Z"
command = "redo"

[[keymaps]]
key = "meta+x"
command = "clipboard_cut"

[[keymaps]]
key = "meta+c"
command = "clipboard_copy"

[[keymaps]]
key = "meta+v"
command = "clipboard_paste"

[[keymaps]]
key = "meta+right"
command = "word_forward"
mode = "i"

[[keymaps]]
key = "meta+left"
command = "word_backward"
mode = "i"

[[keymaps]]
key = "meta+backspace"
command = "delete_word_backward"
mode = "i"

[[keymaps]]
key = "meta+delete"
command = "delete_word_forward"
mode = "i"

[[keymaps]]
key = "meta+|"
command = "match_pairs"
mode = "i"

[[keymaps]]
key = "meta+/"
command = "toggle_line_comment"

[[keymaps]]
key = "meta+]"
command = "indent_line"

[[keymaps]]
key = "meta+["
command = "outdent_line"

# ------------------------------------ Multi cursor -------------------------------------

[[keymaps]]
key = "alt+meta+up"
command = "insert_cursor_above"
mode = "i"

[[keymaps]]
key = "alt+meta+down"
command = "insert_cursor_below"
mode = "i"

[[keymaps]]
key = "meta+l"
command = "select_current_line"
mode = "i"

[[keymaps]]
key = "meta+L"
command = "select_all_current"
mode = "i"

[[keymaps]]
key = "meta+u"
command = "select_undo"
mode = "i"

[[keymaps]]
key = "meta+d"
command = "select_next_current"
mode = "i"

[[keymaps]]
key = "meta+k meta+d"
command = "select_skip_current"
mode = "i"

# ------------------------------------ File Management --------------------------------

[[keymaps]]
key = "meta+s"
command = "save"

[[keymaps]]
key = "meta+o"
command = "open_file"

# ----------------------------------- Editor Management -------------------------------

[[keymaps]]
key = "meta+w"
command = "split_close"

[[keymaps]]
key = "meta+k f"
command = "close_folder"

[[keymaps]]
key = "meta+\\"
command = "split_vertical"

# --------------------------------- Rich Lanaguage Editing ----------------------------

[[keymaps]]
key = "ctrl+space"
command = "get_completion"
mode = "i"

[[keymaps]]
key = "meta+i"
command = "get_completion"
mode = "i"

[[keymaps]]
key = "meta+."
command = "show_code_actions"

# --------------------------------- Display -------------------------------------------

[[keymaps]]
key = "meta+E"
command = "toggle_file_explorer"

[[keymaps]]
key = "meta+F"
command = "toggle_search"

[[keymaps]]
key = "meta+X"
command = "toggle_plugin"

[[keymaps]]
key = "meta+M"
command = "toggle_problem"

# ------------------------------------ Navigation -------------------------------------

[[keymaps]]
key = "meta+O"
command = "palette.symbol"

[[keymaps]]
key = "ctrl+g"
command = "palette.line"
