white = "#fafafa"
black = "#383a42"
grey = "#E5E5E6"
light_grey = "#f2f2f2"
blue = "#526FFF"
red = "#e51400"
yellow = "#e9a700"
green = "#50A14F"
purple = "#A626A4"

"lapce.active_tab" = "$white"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#b4b4b4"

"editor.background" = "$white"
"editor.foreground" = "$black"
"editor.dim" = "#A0A1A7"
"editor.caret" = "$blue"
"editor.selection" = "$grey"
"editor.current_line" = "$light_grey"

"palette.background" = "#eaeaeb"
"palette.current" = "#dbdbdc"

"completion.background" = "#eaeaeb"
"completion.current" = "#dbdbdc"

"panel.background" = "#eaeaeb"
"panel.current" = "#dbdbdc"

"status.background" = "#eaeaeb"
