white = "#fafafa"
black = "#383a42"
light_grey = "#f2f2f2"
blue = "#526FFF"
red = "#e51400"
yellow = "#e9a700"
green = "#50A14F"
purple = "#A626A4"

"editor.background" = "$white"
"editor.foreground" = "$black"
"editor.line_highlight" = "#f2f2f2"
"editor.caret" = "$blue"
"editor.selection" = "#E5E5E6"

caret = "#526FFF"
comment = "#A0A1A7"
selection = "#E5E5E6"
error = "#e51400"
warn = "#e9a700"

"type.builtin" = "#0184bc"
builtinType = "#0184bc"

function = "#4078f2"
method = "#4078f2"
"function.method" = "#4078f2"

string = "#50A14F"

constant = "#986801"

selfKeyword = "#A626A4"
keyword = "#A626A4"

number = "#c18401"
type = "#c18401"
typeAlias = "#c18401"
interface = "#c18401"
struct = "#c18401"
structure = "#c18401"
enum = "#c18401"
attribute = "#c18401"

property = "#e45649"
enumMember = "#e45649"
"enum-member" = "#e45649"
field = "#e45649"
