[package]
name = "lapce-core"
version = "0.0.1"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.7"
xi-rpc = { path = "../../xi-editor/rust/rpc/" }
serde_json = "1.0.59"
