keymaps = [
    { key = "ctrl+meta+p", command = "palette" },
    { key = "esc", command = "palette.cancel", when = "palette_focus" },
    { key = "ctrl+m", command = "list.select", when = "list_focus" },
    { key = "enter", command = "list.select", when = "list_focus" },
    { key = "ctrl+p", command = "list.previous", when = "list_focus" },
    { key = "ctrl+n", command = "list.next", when = "list_focus" },
    { key = "ctrl+b", command = "left", mode = "i" },
    { key = "ctrl+f", command = "right", mode = "i" },
    { key = "ArrowRight", command = "right" },
    { key = "ArrowLeft", command = "left" },
    { key = "ArrowUp", command = "up" },
    { key = "ArrowDown", command = "down" },
    { key = "ctrl+u", command = "delete_to_beginning_of_line", mode = "i" },
    { key = "ctrl+h", command = "delete_backward", mode = "i" },
    { key = "ctrl+w", command = "delete_word_backward", mode = "i" },
    { key = "backspace", command = "delete_backward", mode = "i" },
    { key = "esc", command = "normal_mode", mode = "i" },
    { key = "enter", command = "insert_new_line", mode = "i" },
    { key = "ctrl+m", command = "insert_new_line", mode = "i" },
    { key = "G", command = "go_to_line_deault_last", mode = "nv" },
    { key = "g g", command = "go_to_line_deault_first", mode = "nv" },
    { key = "h", command = "left", mode = "nv" },
    { key = "j", command = "down", mode = "nv" },
    { key = "k", command = "up", mode = "nv" },
    { key = "l", command = "right", mode = "nv" },
    { key = "a", command = "append", mode = "n" },
    { key = "A", command = "append_end_of_line", mode = "n" },
    { key = "i", command = "insert_mode", mode = "nv" },
    { key = "o", command = "new_line_below", mode = "nv" },
    { key = "0", command = "line_start", mode = "nv" },
    { key = "$", command = "line_end", mode = "nv" },
    { key = "w", command = "word_foward", mode = "nv" },
    { key = "e", command = "word_end_foward", mode = "nv" },
    { key = "b", command = "word_backward", mode = "nv" },
    { key = "O", command = "new_line_above", mode = "nv" },
    { key = "ctrl+e", command = "scroll_down", mode = "nv" },
    { key = "ctrl+y", command = "scroll_up", mode = "nv" },
    { key = "ctrl+u", command = "page_up", mode = "nv" },
    { key = "ctrl+d", command = "page_down", mode = "nv" },
    { key = "meta+;", command = "split_vertical", mode = "n" },
    { key = "meta+g", command = "split_horizontal", mode = "n" },
    { key = "ctrl+w l", command = "split_right", mode = "n" },
    { key = "meta+l", command = "split_right", mode = "n" },
    { key = "ctrl+w h", command = "split_left", mode = "n" },
    { key = "meta+h", command = "split_left", mode = "n" },
    { key = "meta+x", command = "split_exchange", mode = "n" },
]
