keymaps = [
    { key = "ctrl+meta+p", command = "palette" },
    { key = "esc", command = "palette.cancel", when = "palette_focus" },
    { key = "ctrl+m", command = "list.select", when = "list_focus" },
    { key = "enter", command = "list.select", when = "list_focus" },
    { key = "ctrl+p", command = "list.previous", when = "list_focus" },
    { key = "ctrl+n", command = "list.next", when = "list_focus" },
    { key = "ctrl+b", command = "left", mode = "i" },
    { key = "ctrl+f", command = "right", mode = "i" },
    { key = "ArrowRight", command = "right" },
    { key = "ArrowLeft", command = "left" },
    { key = "ctrl+u", command = "delete_to_beginning_of_line", mode = "i" },
    { key = "ctrl+h", command = "delete_backward", mode = "i" },
    { key = "backspace", command = "delete_backward", mode = "i" },
    { key = "h", command = "left", mode = "nv" },
    { key = "j", command = "down", mode = "nv" },
    { key = "k", command = "up", mode = "nv" },
    { key = "l", command = "right", mode = "nv" },
    { key = "meta+;", command = "split_vertical", mode = "n" },
    { key = "meta+g", command = "split_horizontal", mode = "n" },
    { key = "meta+l", command = "split_right", mode = "n" },
    { key = "meta+h", command = "split_left", mode = "n" },
    { key = "meta+x", command = "split_exchange", mode = "n" },
]
