name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Rename
        run: |
          cp ./target/release/lapce.exe ./target/release/Lapce-portable.exe
      - name: Upload portable executable
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/release/Lapce-portable.exe
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          
      - name: Install WiX
        run: nuget install WiX
      - name: Crate msi installer
        run: |
          ./WiX.*/tools/candle.exe -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./lapce.wixobj" "extra/windows/wix/lapce.wxs"
          ./WiX.*/tools/light.exe -ext WixUIExtension -ext WixUtilExtension \
            -out "./Lapce-installer.msi" -sice:ICE61 -sice:ICE91 \
            "./lapce.wixobj"
      - name: Upload msi installer
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Lapce-installer.msi
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

  macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Rename
        run: |
          cp ./target/release/macos/Lapce.dmg ./target/release/macos/Lapce-macos.dmg
      - name: Upload Application
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/release/macos/Lapce-macos.dmg
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
